### ISSUE TITLE
Dynamically link to brotli

### ISSUE THREAD

**Issue by matbech** [saucecontrol/Brotli-IIS#1]
Thank you for providing the source of the module. I was thinking whether you would consider dynamically linking to brotli? This has several benefits:

- The brotli.dll (the actual brotli implementation and not the IIS module) can be replaced by the user. E.g. to test an optimized version
- Less maintenance of the IIS module itself. The dll can be stable and doesn't require to be updated with every new brotli version.

Thank you

**Comment by saucecontrol** [comment]
I thought about that as I was publishing my third consecutive release with zero updates to my own code. 😆 

Really, the reason I statically linked everything is because
1) Google has been inconsistent about including Windows binaries for their releases (they did for 1.0.4 but not 1.0.5)
2) There's not just 1 brotli dll.  You need libbrotlicommon.dll and libbrotlienc.dll (if they build them).  And those dynamically link MSVCRT.dll, which is just another thing for people to worry about when deploying.  For something like this, a single dll is way easier.
3) Google's builds (if they do them) still produce sub-optimal code for Windows because they fall back to a slow version of `ctz` and `clz`.  I made a PR to use the VC++ intrinsics for those to get parity with the GCC builds, but they didn't accept it or comment on it.  I expect they'll get around to that someday, but for now, my builds are faster.
4) If someone is comfortable with building their own libbrotlienc, they could certainly build their own version of the IIS module since the code is all here.  My packaged versions are more for people who aren't comfortable with C.

This is one of those cases where I wanted something and couldn't find it, so I wrote it and offered it up for anyone else who might be looking.  I spent about an hour coding, two hours testing, and three hours writing documentation.  And now I'm just keeping it up to date because Google isn't providing good Windows binaries anyway.  If that changes, I'll probably reconsider my own packaging strategy again.

**Comment by matbech** [comment]
Thank you for the explanation. Let's hope we see some more Windows love from Google in the future.
